name: 构建
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出代码库
        uses: actions/checkout@v6

      - name: 验证Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: 设置JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: 使 gradle wrapper 可执行
        run: chmod +x ./gradlew

      - name: 构建
        run: ./gradlew build

      - name: 抓取构建产物
        uses: actions/upload-artifact@v7
        with:
          name: 构建产物
          path: build/libs/myfirstmod-1.0.0.jar